-- Create table
create table WS_METHOD
(
  id             NUMBER generated by default as identity,
  method_name    VARCHAR2(500),
  crud_operation VARCHAR2(10)
)
tablespace DPMT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table WS_METHOD
  add constraint WS_METHOD_PK primary key (ID)
  using index 
  tablespace DPMT
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


-- Create table
create table WS_PROTOCOL
(
  id            NUMBER(12) not null,
  action_id     NUMBER(2) not null,
  method_id     NUMBER(2) not null,
  request       CLOB,
  request_time  DATE not null,
  response      CLOB,
  response_time DATE not null,
  system_err    VARCHAR2(4000)
)
tablespace DPMT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table WS_PROTOCOL
  add constraint WS_PROTOCOL_PK primary key (ID)
  using index 
  tablespace DPMT
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
alter table WS_PROTOCOL
  add constraint WS_PROTOCOL_F1 foreign key (METHOD_ID)
  references WS_METHOD (ID);
alter table WS_PROTOCOL
  add constraint WS_PROTOCOL_FK foreign key (ACTION_ID)
  references WS_R_ACTION (ID);


-- Create table
create table WS_R_ACTION
(
  id         NUMBER not null,
  state_name VARCHAR2(250)
)
tablespace DPMT
  pctfree 10
  initrans 1
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );
-- Create/Recreate primary, unique and foreign key constraints 
alter table WS_R_ACTION
  add constraint WS_R_ACTION_PK primary key (ID)
  using index 
  tablespace DPMT
  pctfree 10
  initrans 2
  maxtrans 255
  storage
  (
    initial 64K
    next 1M
    minextents 1
    maxextents unlimited
  );


-- Create table
create table WS_R_METHOD
(
  id          NUMBER,
  method_name VARCHAR2(500)
)
tablespace DPMT
  pctfree 10
  initrans 1
  maxtrans 255;


-- Create sequence 
create sequence WS_PROTOCOL_SQ
minvalue 1
maxvalue 9999999999999999999999999999
start with 321
increment by 1
cache 20;

  
commit;
